export const GET_TICKETS = 'GET_TICKETS';
export const CREATE_NEW_TICKET = 'CREATE_NEW_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';
export const UPDATE_TICKET = 'UPDATE_TICKET';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const FILTER_TICKETS_BY_USERID = 'FILTER_TICKETS_BY_USERID';
export const FILTER_TICKETS_BY_SEARCH = 'FILTER_TICKETS_BY_SEARCH';
export const REMOVE_USER_FILTER = 'REMOVE_USER_FILTER';
export const CLEAR_ALL_FILTERS = 'CLEAR_ALL_FILTERS';

