version: "3"
services:
  react-app:
    image: react-app-production:${ENV}
    restart: unless-stopped
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - mern-app
  api-server:
    image: api-server
    restart: unless-stopped
    env_file: ./api/.env
    ports:
      - "3000:3000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local
