export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_ONE_COLUMN_TICKETS_ORDER = 'UPDATE_COLUMN_TICKETS_START';
export const UPDATE_TWO_COLUMNS_TICKETS_ORDER = 'UPDATE_TWO_COLUMNS_TICKETS_ORDER';
export const UPDATE_COLUMN_ORDER = 'UPDATE_COLUMN_ORDER';
export const FAIL_UPDATE_ORDER = 'FAIL_UPDATE_ORDER';
export const SUCCESS_UPDATE_ORDER = 'SUCCESS_UPDATE_ORDER';
export const UPDATE_COLUMN_WITH_NEW_TICKET = 'UPDATE_COLUMN_WITH_NEW_TICKET';
export const UPDATE_COLUMN_WITH_DELETED_TICKET = 'UPDATE_COLUMN_WITH_DELETED_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';
export const UPDATE_TICKET_STATUS = 'UPDATE_TICKET_STATUS';
export const SET_CURRENT_PROJECT_ID = 'SET_CURRENT_PROJECT_ID';

