export const GET_PROJECTS = 'GET_PROJECTS';
export const UPDATE_ONE_COLUMN_TICKETS_ORDER = 'UPDATE_COLUMN_TICKETS_START';
export const UPDATE_TWO_COLUMNS_TICKETS_ORDER = 'UPDATE_TWO_COLUMNS_TICKETS_ORDER';
export const UPDATE_COLUMN_ORDER = 'UPDATE_COLUMN_ORDER';
export const FAIL_UPDATE_ORDER = 'FAIL_UPDATE_ORDER';
export const SUCCESS_UPDATE_ORDER = 'SUCCESS_UPDATE_ORDER';

